language: node_js
node_js: '10'
branches:
  only:
    - master

script: npm run build && npm run export

before_deploy: cp out_patch/* out && touch out/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  local_dir: out
  on:
    branch: master

