language: node_js
node_js: '10'
script: npm run build && npm run export

deploy:
  - provider: firebase
    project: prod
    edge: true
    on:
      branch: master

  - provider: firebase
    project: dev
    edge: true
    on:
      branch: develop
